[tool.black]
color = true
extend-exclude = '''
/(
  | migrations
)/
'''
line_length = 119
target_version = ["py39"]

[tool.isort]
color_output = true
extend_skip = ["migrations"]
line_length = 119
multi_line_output = 3
profile = "black"
py_version = 39
